version: '3.8'

services:
  postgres:
    image: postgres:16  # Versão mais recente e estável
    restart: always
    environment:
      POSTGRES_USER: douglas       # Seu usuário
      POSTGRES_PASSWORD: Dougras1  # Sua senha
      POSTGRES_DB: controlei  # Nome do banco
    ports:
      - "5432:5432"  # Porta padrão do PostgreSQL