services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Dougras1
      MYSQL_DATABASE: Finance-organizer
      MYSQL_USER: douglas
      MYSQL_PASSWORD: Dougras1
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --skip-log-bin

volumes:
  mysql_data: